/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PiedavajumsRouteImport } from './routes/piedavajums'
import { Route as ParMumsRouteImport } from './routes/par-mums'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as AtsauksmesRouteImport } from './routes/atsauksmes'
import { Route as IndexRouteImport } from './routes/index'

const PiedavajumsRoute = PiedavajumsRouteImport.update({
  id: '/piedavajums',
  path: '/piedavajums',
  getParentRoute: () => rootRouteImport,
} as any)
const ParMumsRoute = ParMumsRouteImport.update({
  id: '/par-mums',
  path: '/par-mums',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsauksmesRoute = AtsauksmesRouteImport.update({
  id: '/atsauksmes',
  path: '/atsauksmes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atsauksmes': typeof AtsauksmesRoute
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/piedavajums': typeof PiedavajumsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atsauksmes': typeof AtsauksmesRoute
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/piedavajums': typeof PiedavajumsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atsauksmes': typeof AtsauksmesRoute
  '/kontakti': typeof KontaktiRoute
  '/par-mums': typeof ParMumsRoute
  '/piedavajums': typeof PiedavajumsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atsauksmes' | '/kontakti' | '/par-mums' | '/piedavajums'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atsauksmes' | '/kontakti' | '/par-mums' | '/piedavajums'
  id:
    | '__root__'
    | '/'
    | '/atsauksmes'
    | '/kontakti'
    | '/par-mums'
    | '/piedavajums'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsauksmesRoute: typeof AtsauksmesRoute
  KontaktiRoute: typeof KontaktiRoute
  ParMumsRoute: typeof ParMumsRoute
  PiedavajumsRoute: typeof PiedavajumsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/piedavajums': {
      id: '/piedavajums'
      path: '/piedavajums'
      fullPath: '/piedavajums'
      preLoaderRoute: typeof PiedavajumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/par-mums': {
      id: '/par-mums'
      path: '/par-mums'
      fullPath: '/par-mums'
      preLoaderRoute: typeof ParMumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atsauksmes': {
      id: '/atsauksmes'
      path: '/atsauksmes'
      fullPath: '/atsauksmes'
      preLoaderRoute: typeof AtsauksmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsauksmesRoute: AtsauksmesRoute,
  KontaktiRoute: KontaktiRoute,
  ParMumsRoute: ParMumsRoute,
  PiedavajumsRoute: PiedavajumsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
